name: Master Trigger

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  Trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: workflow-dispatcher
      uses: ./.github/actions/workflow-dispatcher
      with:
        token: ${{ secrets.PUSH_TOKEN }}
        event_type: Builder
        workflow_file_name: builder.yml
        input: '{ "image_name": "bastillion-dev", "image_ver": "latest", "git_ref": "master" }'
        wait_time: 5
        max_time: 600