name: Master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_DEPLOY_KEY }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          BASTILLION_VERSION=$(curl -sSLq https://api.github.com/repos/n-stone/docker-bastillion/releases/latest | jq -r ".name")
          BASTILLION_FILENAME_VERSION=$(echo $BASTILLION_VERSION | sed -r 's/(.*)\./\1_/')
          # Fix for 3.14.0
          if [ "${#BASTILLION_FILENAME_VERSION}" -lt 7 ]; then BASTILLION_FILENAME_VERSION=$(echo "${BASTILLION_FILENAME_VERSION}0"); fi
          docker buildx build -t "${DOCKER_USER}/bastillion:dev" \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg BASTILLION_VERSION=${BASTILLION_VERSION} \
            --build-arg BASTILLION_FILENAME_VERSION=${BASTILLION_FILENAME_VERSION} \
            --push .
  test-ubuntu:
    runs-on: ubuntu-latest
    needs: build-ubuntu
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3    
      -
        name: Setup tests
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}        
        run: |
          mkdir $(pwd)/keydb
          chmod 777 $(pwd)/keydb
          docker run -d --rm --name bastillion -v $(pwd)/keydb:/keydb "${DOCKER_USER}/bastillion:dev"
          docker exec -u 0 bastillion apt install net-tools
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
          inspec --chef-license=accept
      -
        name: InSpec Integration Test
        run: |
          inspec exec ./test/ubuntu -t docker://bastillion
      -
        name: Check logs
        run: |
          if $(docker logs bastillion | grep -q Exception -q); then
            docker logs bastillion
            exit 1
          else:
            echo "No Exceptions"
          fi
      -
        name: Teardown
        run: |
          docker container stop bastillion
          rm -rf keydb
  build-alpine:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_DEPLOY_KEY }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          BASTILLION_VERSION=$(curl -sSLq https://api.github.com/repos/n-stone/docker-bastillion/releases/latest | jq -r ".name")
          BASTILLION_FILENAME_VERSION=$(echo $BASTILLION_VERSION | sed -r 's/(.*)\./\1_/')
          # Fix for 3.14.0
          if [ "${#BASTILLION_FILENAME_VERSION}" -lt 7 ]; then BASTILLION_FILENAME_VERSION=$(echo "${BASTILLION_FILENAME_VERSION}0"); fi
          docker buildx build -t "${DOCKER_USER}/bastillion:dev-alpine" \
            --platform linux/amd64,linux/arm64 \
            --build-arg BASTILLION_VERSION=${BASTILLION_VERSION} \
            --build-arg BASTILLION_FILENAME_VERSION=${BASTILLION_FILENAME_VERSION} \
            --file ./Dockerfile.alpine --push .
  test-alpine:
    runs-on: ubuntu-latest
    needs: build-alpine
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup tests
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          mkdir $(pwd)/keydb
          chmod 777 $(pwd)/keydb
          docker run -d --rm --name bastillion -v $(pwd)/keydb:/keydb "${DOCKER_USER}/bastillion:dev-alpine"
          docker exec -u 0 bastillion apk --no-cache add net-tools
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
          inspec --chef-license=accept
      -
        name: InSpec Integration Test
        run: |
          inspec exec ./test/alpine -t docker://bastillion
      -
        name: Check logs
        run: |
          if $(docker logs bastillion | grep -q Exception); then
            docker logs bastillion
            exit 1
          else:
            echo "No Exceptions"
          fi
      -
        name: Teardown
        run: |
          docker container stop bastillion
          rm -rf keydb