name: Release Trigger

on:
  push:
    tags:
    - '*'

jobs:
  Trigger-Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}
      - name: workflow-dispatcher
        uses: ./.github/actions/workflow-dispatcher
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          event_type: Builder
          workflow_file_name: builder.yml
          input: '{ "image_name": "bastillion", "image_ver": "${{ steps.get_version.outputs.version }}", "git_ref": "${{ steps.get_version.outputs.version }}" }'
          wait_time: 5
          max_time: 600