name: Refresh base images

on: 
  schedule:
   - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.TAGS }}
    steps:
      - 
        id: matrix
        run: |
          python -c "
          import requests, json
          docker_bastillion_releases = json.loads(requests.get('https://api.github.com/repos/n-stone/docker-bastillion/git/matching-refs/tags').content.decode('utf-8'))
          tags = [x['ref'].split('/')[-1] for x in docker_bastillion_releases]
          print('::set-output name=TAGS::{"tag":' + json.dumps(tags) + '}')
          "
  Trigger-Builds:
    runs-on: ubuntu-latest
    needs: Setup
    strategy:
      matrix: ${{fromJson(needs.Setup.outputs.matrix)}}
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3
      - name: workflow-dispatcher
        uses: ./.github/actions/workflow-dispatcher
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          event_type: Builder
          workflow_file_name: builder.yml
          input: '{ "image_name": "bastillion", "image_ver": "${{ matrix.tag }}", "git_ref": "${{ matrix.tag }}" }'
          wait_time: 5
          max_time: 600